name: 03-workflow-runners
on: 
    push:
    workflow_dispatch:

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on Ubuntu!"
                echo "The OS is: $RUNNER_OS"
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: |
                echo "This job is running on Windows!"
                echo "The OS is: $RUNNER_OS"
    macos-echo:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run: |
               echo "This job is running on MacOS!"
               echo "The OS is: $RUNNER_OS"