name: 05-1-event-filters-activity-types
on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "I've been triggered by a(n) ${{ github.event_name }} event!"